### ISSUE TITLE
Adição de validação de complexidade de senha

### ISSUE THREAD

**Issue by Yagasaki7K** [Luciano655dev/better-format#1]
Senhas fortes são essenciais para proteger suas contas online. No entanto, muitos usuários acabam criando senhas simples demais, o que as torna mais vulneráveis a ataques cibernéticos.

Uma forma de melhorar a segurança das senhas é validar sua complexidade durante o cadastro. Isso pode ser feito verificando se a senha atende aos seguintes requisitos:

Tamanho: Pelo menos 8 caracteres, sendo recomendado um mínimo de 12 caracteres.
Caracteres: Devem incluir letras maiúsculas, minúsculas, números e caracteres especiais.
Complexidade: Devem ser difíceis de adivinhar, evitando palavras ou frases comuns, nomes de pessoas, datas de nascimento, etc.

**Comment by Luciano655dev** [comment]
Função já adicionada! Ainda será melhorada com o tempo.
