### ISSUE TITLE
Adição de validação de endereços

### ISSUE THREAD

**Issue by Yagasaki7K** [Luciano655dev/better-format#2]
Atualmente, o pacote não realiza nenhuma validação de endereços. Isso pode ser um problema, pois permite que os usuários insiram endereços inválidos ou incorretos em alguns casos de uso.

Para melhorar a funcionalidade do pacote, proponho a adição de validação de endereços. A validação deve verificar se o endereço atende aos seguintes requisitos:

Formato: O endereço deve seguir o formato específico do país.
Caracteres: O endereço deve conter apenas caracteres permitidos para o formato do país.
Tamanho: O endereço deve ter o tamanho correto para o formato do país.

A validação pode ser implementada usando uma biblioteca de validação de endereços existente, como o Google Maps Geocoding API: https://developers.google.com/maps/documentation/geocoding/overview

**Comment by Luciano655dev** [comment]
A função acabou de ser adicionada!

Ela valida um CEP e pega as informações do endereço pela API ViaCep (https://viacep.com.br)

Primeira função assíncrona adicionada, abrindo espaço para mais funções que dependam de alguma API, ampliando o leque de possibilidades. Qualquer nova Issue, fique a vontade para postar!
