### ISSUE TITLE
Adição de validação de CNPJ

### ISSUE THREAD

**Issue by Yagasaki7K** [Luciano655dev/better-format#5]
Atualmente, o pacote oferece recursos valiosos para formatação e recuperação de informações sobre variáveis. No entanto, percebemos a necessidade de incorporar uma funcionalidade adicional de validação de CNPJ para tornar o pacote ainda mais abrangente.

Esta adição fortalecerá ainda mais a utilidade do pacote, permitindo que os desenvolvedores lidem não apenas com a formatação e recuperação de informações sobre variáveis, mas também com a validação de CNPJ, tornando-o uma solução completa para manipulação de dados relacionados a variáveis.

Uma referência que pode ser boa para o uso da validação é o https://www.npmjs.com/package/cpf-cnpj-validator

**Comment by Luciano655dev** [comment]
A função já foi adicionada!

Tentei fazer com que ela também retornasse as informações, porém, para isso, é preciso chamar a API CNPJA https://cnpja.com que, além de precisar de autenticação também é paga depois do teste gratuito.

Mesmo assim, a função retorna um Object { isValid: bool, cleanCNPJ: string) caso o cliente queira fazer a autenticação na API logo após verificar se o CPF é válido.
